FROM node:14 AS build
WORKDIR /my-app

ENV PATH /my-app/node_modules/.bin:$PATH

#COPY ./ .
COPY package.json ./
COPY package-lock.json ./

RUN npm install
COPY . ./

RUN npm run build

# CMD ["npm", "start"]


# # nginx 
FROM nginx:latest
COPY --from=build /my-app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx","-g", "daemon off;"]
