global:
  scrape_interval:   10s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'streamingwars-monitoring'

scrape_configs:
- job_name:       'streamingwars'

  # Override the global default and scrape targets from this job every 10 seconds.
  scrape_interval: 5s
  metrics_path: '/actuator/prometheus'

  static_configs:
  - targets: ['172.17.0.1:8090']
    labels:
      application: 'streamingwars'

- job_name: 'prometheus'

  scrape_interval: 5s

  static_configs:
  - targets: ['172.17.0.1:9090']
